### ISSUE TITLE
Pretrained model after stage 1

### ISSUE THREAD

**Issue by lrxsxdl** [ahaliassos/RealForensics#1]
Hi, thanks for your brilliant work! Would you please provide your pretrained model after stage 1 but before stage 2?

**Comment by ahaliassos** [comment]
Hi,

Here's a pre-trained model after stage 1: https://drive.google.com/file/d/1h9e-99tcfnjk_9aEMokCt6F3SsLlKCIf/view?usp=sharing

**Comment by lrxsxdl** [comment]
@ahaliassos Thanks a million!

**Comment by lrxsxdl** [comment]
Hi，I found that the model in your provided link only contained the video branch. Could you please provide the audio branch? Thanks again!

**Comment by lrxsxdl** [comment]
Hi，I found that the model in your provided link only contained the video branch. Could you please provide the audio branch? Thanks again!
&nbsp;


生锈的犁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月25日(星期五) 晚上9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ahaliassos/RealForensics] Pretrained model after stage 1 (Issue #1)





 
Closed #1 as completed.

**Comment by yinghuozijin** [comment]
> Hi，I found that the model in your provided link only contained the video branch. Could you please provide the audio branch? Thanks again!

@lrxsxdl  Hello, did you get the audio model? I also need it.
