### ISSUE TITLE
how can i use the project you advised to generate 68 landmarks point in a .npy file ?

### ISSUE THREAD

**Issue by AWGiaGia** [ahaliassos/RealForensics#8]
The project 'Pytorch_Retinaface' seems cound't generate the 68 landmarks your code need

**Comment by nguyenvulong** [comment]
have you tried the other one: `face-alignment`?

**Comment by nguyenvulong** [comment]
Nice

**Comment by diksham-flwls** [comment]
I am using `face-alignment` to generate landmarks but it gives very shaky face crops. I am curious if its a standard practice to use landmarks to generate bounding box or if its better to use a face detection module to get more stable outputs?
